version: "3.8"
services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"
    env_file:
      - .env
  postgres:
    container_name: postgres
    image: "postgres:latest"
    restart: always
    env_file:
      - .env
    networks:
      - postgres
  redis:
    container_name: redis
    image: "redis:latest"
    restart: always
    env_file:
      - .env
    networks:
      - redis
    depends_on:
      - postgres
  be:
    container_name: be
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - postgres
      - redis
    tty: true
  fe:
    container_name: fe
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge