version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
    env_file:
      - .env
  redis:
    image: "redis:latest"
    restart: always
    env_file:
      - .env
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"
  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .env