version: "3.8"
services:
  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
