import { QueryProvider } from "@/ui/client-providers";
import { Splash } from "@/ui/Splash";
import type { AppProps } from "next/app";
import Head from "next/head";
import { createGlobalStyle, ThemeProvider } from "styled-components";
import { Roboto } from "@next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={roboto.className}>
        <ThemeProvider
          theme={{
            colors: {
              primary: "#6500fc",
            },
          }}
        >
          <GlobalStyles />
          <Splash>
            <QueryProvider>
              <Component {...pageProps} />
            </QueryProvider>
          </Splash>
        </ThemeProvider>
      </div>
    </>
  );
}

const GlobalStyles = createGlobalStyle`
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html,
body {
  max-width: 100vw;
}

body {}

a {
  color: inherit;
  text-decoration: none;
}
`;
